Repository alefragnani/vscode-read-only-indicator, pull requests merged in 2021-11, with the labels that each got.

#62 Add Contributing (Closes #56)
  CONTRIBUTING.md
Labels: documentation

#60 Support folder level file access for MacOS and Linux
  package.json
  src/operations.ts
Labels: good first issue, MacOS

#64 Bump devDependencies (Closes #61)
  package-lock.json
  package.json
  src/test/runTest.ts
  tsconfig.json
  webpack.config.js
Labels: internal
